name: adyen_client_side_encryption
description: Adyen card client side encryption
version: 0.0.5
homepage: https://github.com/lightyeardev/adyen-client-side-encryption

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.24.1"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.golightyear.adyen_client_side_encryption
        pluginClass: AdyenClientSideEncryptionPlugin
      ios:
        pluginClass: AdyenClientSideEncryptionPlugin
